# Generated by Django 5.2.6 on 2025-12-10 04:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calendarevent_app', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='calendar_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
