# Generated by Django 5.2.6 on 2025-11-29 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarevent_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='type',
            field=models.CharField(choices=[('Deadline', 'Deadline'), ('Meeting', 'Meeting'), ('Event', 'Event')], default='Event', max_length=50),
        ),
    ]
