# Generated by Django 5.2.6 on 2025-10-11 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendarevent_app', '0002_calendarevent_project_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendarevent',
            name='project_id',
        ),
    ]
