# Generated by Django 5.2.6 on 2025-10-11 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0004_task_project_id'),
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='notification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_app.notification'),
        ),
        migrations.AddField(
            model_name='task',
            name='users',
            field=models.ManyToManyField(through='task_app.Assignment', to='user_app.user'),
        ),
    ]
