# Generated by Django 5.2.6 on 2025-09-27 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project_app', '0001_initial'),
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimelineEntry',
            fields=[
                ('timeline_id', models.IntegerField(primary_key=True, serialize=False)),
                ('project_id', models.ManyToManyField(to='project_app.project')),
                ('user_id', models.ManyToManyField(to='user_app.user')),
            ],
        ),
    ]
