# Generated by Django 5.2.6 on 2025-09-30 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0001_initial'),
        ('timeline_app', '0001_initial'),
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timelineentry',
            name='project_id',
        ),
        migrations.RemoveField(
            model_name='timelineentry',
            name='user_id',
        ),
        migrations.AddField(
            model_name='timelineentry',
            name='project_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='project_app.project'),
        ),
        migrations.AddField(
            model_name='timelineentry',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_app.user'),
        ),
    ]
