# Generated by Django 5.2.6 on 2025-10-11 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0005_task_notification_task_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='notification',
            new_name='notification_id',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='users',
            new_name='user_id',
        ),
    ]
