# Generated by Django 5.2.6 on 2025-11-25 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline_app', '0003_timelineentry_action_timelineentry_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timelineentry',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='timelineentry',
            name='action',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='timelineentry',
            name='details',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='timelineentry',
            name='timeline_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
