# Generated by Django 5.2.6 on 2025-09-27 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='user_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='KanbanColumn',
            fields=[
                ('column_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_index', models.PositiveIntegerField(default=0)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='project_app.project')),
            ],
        ),
    ]
