# Generated by Django 5.2.6 on 2025-10-11 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0001_initial'),
        ('task_app', '0006_rename_notification_task_notification_id_and_more'),
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kanbancolumn',
            name='project_id',
        ),
        migrations.AddField(
            model_name='kanbancolumn',
            name='task_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kanban_columns', to='task_app.task'),
        ),
        migrations.RemoveField(
            model_name='project',
            name='user_id',
        ),
        migrations.AddField(
            model_name='project',
            name='user_id',
            field=models.ManyToManyField(related_name='projects', to='user_app.user'),
        ),
    ]
