# Generated by Django 5.2.6 on 2025-10-18 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0002_remove_kanbancolumn_project_id_kanbancolumn_task_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kanbancolumn',
            name='project_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='project_app.project'),
            preserve_default=False,
        ),
    ]
